#!/usr/bin/env bash

function is_root {
    if [ ${EUID:-$(id -u)} -eq 0 ]; then
        return 0
    fi
    return 1
}

export VSCS_CONFIG="$(is_root && echo "${SNAP_DATA}" || echo "${SNAP_USER_DATA}")/config.yaml"
export VSCS_UDD="$(is_root && echo "${SNAP_DATA}" || echo "${SNAP_USER_DATA}")/user-data"
export VSCS_EXT="$(is_root && echo "${SNAP_DATA}" || echo "${SNAP_USER_DATA}")/extensions"
export VSCS_USD="$(is_root && echo "${SNAP_COMMON}" || echo ${SNAP_USER_COMMON})"
export VSCS_SSH="${SNAP_USER_COMMON}/.ssh"

if [ ! -d "${VSCS_UDD}" ]; then
    mkdir -p "${VSCS_UDD}/logs"
fi

if [ ! -d "${VSCS_EXT}" ]; then
    mkdir -p "${VSCS_EXT}"
fi

